assets/urls.py
from django.urls import path
from assets import views

app_name = "assets"

urlpatterns = [
    path('ecs-create', views.EcsCreateView.as_view(), name='ecs-create'),
    path('ecs-list', views.EcsListView.as_view(), name='ecs-list'),
    path('ecs-update-<int:pk>', views.EcsUpdateView.as_view(), name='ecs-update'),
    path('ecs-detail-<int:pk>', views.EcsDetailView.as_view(), name='ecs-detail'),
    path('ecs-delete', views.EcsDeleteView.as_view(), name='ecs-delete'),


    path('api/ecs', views.ApiEcsList.as_view()),
    path('api/ecs/<int:pk>', views.ApiEcsDetail.as_view()),
]

k8s/urls.py
from django.urls import path
from k8s import views

app_name = "k8s"

urlpatterns = [
    path('k8s-node-list', views.K8sNodeListView.as_view(), name='k8s-node-list'),

    path('k8s-service-list', views.K8sServiceListView.as_view(), name='k8s-service-list'),

    path('k8s-pod-list', views.K8sPodListView.as_view(), name='k8s-pod-list'),
    path('k8s-pod-webssh', views.K8sPodWebssh.as_view(), name='k8s-pod-webssh'),
    path('k8s-pod-detail', views.K8sPodDetail.as_view(), name='k8s-pod-detail')
]

seal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from system.views import index
from rest_framework.authtoken import views
from rest_framework.documentation import include_docs_urls
from graphene_django.views import GraphQLView
from seal.schema import schema

API_TITLE = '海豹 API 文档'
API_DESCRIPTION = '海豹 API 文档'

urlpatterns = [
    path('', index),
    path('index', index, name="index"),
    path('system/', include('system.urls', namespace='system')),
    path('assets/', include('assets.urls', namespace='assets')),
    path('k8s/', include('k8s.urls', namespace='k8s')),
    path('admin/', admin.site.urls, ),
    path('api/token', views.obtain_auth_token),
    path('api/docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION, authentication_classes=[],
                                        permission_classes=[])),
    path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),

    path('sql/', include('sql.urls', namespace='sql')),
]

sql/urls.py
from django.urls import path
from sql import views

app_name = "sql"

urlpatterns = [
    path('sql.html', views.SqlDdl.as_view(), name='sql_ddl'),
    path('sql-<str:pk>.html', views.SqlDdlQuery.as_view(), name='sql_query'),
]

system/urls.py
from django.urls import path
from system.views import login_view, UserPasswordUpdateView, logout_view, UserInfo, UserLogout,Menu

app_name = "system"

urlpatterns = [
    path('login', login_view, name="login"),
    path('password_update', UserPasswordUpdateView.as_view(), name="password_update"),
    path('logout', logout_view, name="logout"),


    path('api/user_info', UserInfo.as_view()),
    path('api/logout', UserLogout.as_view()),
    path('menu',Menu.as_view())
]

assets/models.py
from django.db import models


class Ecs(models.Model):
    TYPE_CHOICES = (
        ('阿里云', '阿里云'),
        ('腾讯云', '腾讯云'),
        ('华为云', '华为云'),
        ('亚马逊', '亚马逊'),
        ('其他', '其他'),
        (None,None),
    )
    hostname = models.CharField(max_length=96, verbose_name='主机名', blank=True, null=True, )
    type = models.CharField(choices=TYPE_CHOICES, max_length=16, verbose_name='主机类型', blank=True, null=True, )
    instance_id = models.CharField(max_length=64, verbose_name='实例ID', unique=True)
    instance_name = models.CharField(max_length=96, verbose_name='标签', blank=True, null=True, )
    os_name = models.CharField(max_length=64, verbose_name='系统版本', blank=True, null=True, )
    cpu = models.IntegerField(verbose_name='CPU', blank=True, null=True)
    memory = models.IntegerField(verbose_name='内存', blank=True, null=True)
    private_ip = models.GenericIPAddressField(verbose_name='内网IP', blank=True, null=True)
    public_ip = models.GenericIPAddressField(verbose_name='外网IP', blank=True, null=True)

    c_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间', blank=True)
    u_time = models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间', blank=True)

    class Meta:
        db_table = "ecs"
        verbose_name = "主机"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.hostname

templates/base/_css.html
{% load  static %}

<link href=" {% static  "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static  "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

<link href="{% static  "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css" %} " rel="stylesheet">

<link href="{% static "css/datatables.min.css" %} " rel="stylesheet">

<link href="{% static "css/plugins/select2/select2.min.css" %} " rel="stylesheet">


<link href="{% static  "css/plugins/sweetalert/sweetalert.css" %}" rel="stylesheet">

<link href="{% static "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">


<link href="{% static  "css/plugins/toastr/toastr.min.css" %}" rel="stylesheet">
<link href="{% static  "css/plugins/steps/jquery.steps.css" %}" rel="stylesheet">

<style>
    .select2-container--default .select2-selection--single .select2-selection__rendered {
        line-height: 32px;
    }

    .select2-container .select2-selection--single {
        height: 32px;
    }
</style>

templates/base/_footer.html
  <div class="footer">
            <div class="pull-right">
               <strong>Version 0.3 </strong>
            </div>
            <div>
                <strong>海豹  作者:何全 邮箱: hequan2011@sina.com </strong>
            </div>
        </div>  

templates/base/_js.html
{% load  static %}
<script src="{% static  "js/jquery-3.1.1.min.js" %}"   type="text/javascript" ></script>
<script src="{% static  "js/bootstrap.min.js" %}"></script>
<script src="{% static  "js/plugins/metisMenu/jquery.metisMenu.js" %}"></script>
<script src="{% static  "js/plugins/slimscroll/jquery.slimscroll.min.js" %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  "js/inspinia.js" %} "></script>
<script src="{% static  "js/plugins/pace/pace.min.js" %}"></script>


<script src="{% static  "js/datatables.min.js" %}"></script>

<script src="{% static  "js/plugins/select2/select2.full.min.js" %}"></script>

<!-- Sweet alert -->
<script src="{% static  "js/plugins/sweetalert/sweetalert.min.js" %}"></script>




<script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>


<script>

    $(document).ready(function () {
        $('.dataTables-example').DataTable({


            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
             dom: '<"html5buttons"B>lTfgitp,',
            buttons: [ 'copy', 'csv', 'excel' ]
        });


        $('.dataTables-code').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            bFilter: false,
            "order": [[1, 'desc']],
            "info": false,//是否显示页脚信息
            destroy: true,
            "ordering": false,
            dom: '<"html5buttons"B>lTfgitp,',
            buttons: [],
            lengthMenu: [[-1], ["全部"]],
            "paging": false, // 禁止分页
        });

    });

    $(function () {
        $(".select2").select2();
    });

</script>

templates/base/_nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu chrome-nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    {% if  user.avatar %}
                        <span>
                   <img alt="image" class="img-circle" style="width:48px; height:48px;" src="{{ user.avatar }}"/>
                             </span>
                    {% endif %}

                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">



                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ user }}</strong>

                             </span> <span class="text-muted text-xs block">
                                {% ifequal  user.is_superuser  1 %}
                                    管理员 {% else %}   {{ user.position }} {% endifequal %}

                                <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{% url  "system:password_update" %}">修改密码</a></li>
                        <li><a href="{% url  "system:logout" %}">退出</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    海豹
                </div>
            </li>
            <li>
                <a href="{% url "index" %}"> <i class="fa fa-dashboard"></i> <span class="nav-label">首页</span>
                </a>
            </li>


            <li class="assets">
                <a href="#"> <i class="fa fa-calendar-minus-o"></i> <span class="nav-label">资产管理</span> <span class="fa arrow"> </span></a>


                <ul class="nav nav-second-level">
                    {% if perms.assets.add_ecs %}
                        <li class="ecs-create">
                            <a href="{% url "assets:ecs-create" %}">添加资产</a>
                        </li>
                    {% endif %}
                    {% if perms.assets.view_ecs %}
                        <li class="ecs-list">
                            <a href="{% url "assets:ecs-list" %}">资产列表</a>
                        </li>
                    {% endif %}
                </ul>

            </li>
          {% if perms.k8s.view_ecs %}
            <li class="k8s">
                <a href="#"> <i class="fa fa-bookmark-o"></i> <span class="nav-label">k8s管理</span> <span class="fa arrow"> </span></a>


                <ul class="nav nav-second-level">

                                         <li class="k8s-node-list">
                            <a href="{% url "k8s:k8s-node-list" %}">Node列表</a>
                        </li>

                     <li class="k8s-service-list">
                            <a href="{% url "k8s:k8s-service-list" %}">Service列表</a>
                        </li>

                        <li class="k8s-pod-list">
                            <a href="{% url "k8s:k8s-pod-list" %}">Pod列表</a>
                        </li>

                </ul>
            </li>
 {% endif %}


                    <li class="sql">
                <a href="#"><i class="fa fa-keyboard-o"></i> <span class="nav-label">SQL审核</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="sql_ddl">
                        <a href="{% url "sql:sql_ddl" %}">执行</a></li>

                </ul>
            </li>

            {% ifequal  user.is_superuser  1 %}

                <li>
                    <a href="/admin" target="_blank"><i class="fa fa-gears"></i> <span class="nav-label">管理界面</span>
                    </a>
                </li>
            {% endifequal %}


        </ul>

    </div>
</nav>

templates/base/_navbar-static-top.html
<div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">


                        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
{#            <form role="search" class="navbar-form-custom" action="search_results.html">#}
{#                <div class="form-group">#}
{#                    <input type="text" placeholder="请输入搜索内容" class="form-control" name="top-search" id="top-search">#}
{#                </div>#}
{#            </form>#}



        </div>

   <ul class="nav navbar-top-links navbar-right">
                <li style="padding: 20px">
                    <span class="m-r-sm text-muted welcome-message">欢迎 {{ user  }} 来到 海豹管理后台</span>
                </li>



                <li>
                    <a href="{% url "system:logout" %}">
                        <i class="fa fa-sign-out"></i> 注销
                    </a>
                </li>

            </ul>





            </nav>
        </div>

templates/base/base.html
{% load staticfiles %}
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block  title %}{% endblock %}</title>

    {% include  "base/_css.html" %}
    {% block header-css %}
    {% endblock %}


</head>

<body>
<div id="wrapper">


    {% include "base/_nav.html" %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "base/_navbar-static-top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "base/_footer.html" %}

    </div>
</div>

</body>

{% include  "base/_js.html" %}

{% block footer-js %}
{% endblock %}

</html>