assets/urls.py
from django.urls import path
from assets import views

app_name = "assets"

urlpatterns = [
    path('ecs-create', views.EcsCreateView.as_view(), name='ecs-create'),
    path('ecs-list', views.EcsListView.as_view(), name='ecs-list'),
    path('ecs-update-<int:pk>', views.EcsUpdateView.as_view(), name='ecs-update'),
    path('ecs-detail-<int:pk>', views.EcsDetailView.as_view(), name='ecs-detail'),
    path('ecs-delete', views.EcsDeleteView.as_view(), name='ecs-delete'),


    path('api/ecs', views.ApiEcsList.as_view()),
    path('api/ecs/<int:pk>', views.ApiEcsDetail.as_view()),
]

k8s/urls.py
from django.urls import path
from k8s import views

app_name = "k8s"

urlpatterns = [
    path('k8s-node-list', views.K8sNodeListView.as_view(), name='k8s-node-list'),

    path('k8s-service-list', views.K8sServiceListView.as_view(), name='k8s-service-list'),

    path('k8s-pod-list', views.K8sPodListView.as_view(), name='k8s-pod-list'),
    path('k8s-pod-webssh', views.K8sPodWebssh.as_view(), name='k8s-pod-webssh'),
    path('k8s-pod-detail', views.K8sPodDetail.as_view(), name='k8s-pod-detail')
]

seal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from system.views import index
from rest_framework.authtoken import views
from rest_framework.documentation import include_docs_urls
from graphene_django.views import GraphQLView
from seal.schema import schema

API_TITLE = '海豹 API 文档'
API_DESCRIPTION = '海豹 API 文档'

urlpatterns = [
    path('', index),
    path('index', index, name="index"),
    path('system/', include('system.urls', namespace='system')),
    path('assets/', include('assets.urls', namespace='assets')),
    path('k8s/', include('k8s.urls', namespace='k8s')),
    path('admin/', admin.site.urls, ),
    path('api/token', views.obtain_auth_token),
    path('api/docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION, authentication_classes=[],
                                        permission_classes=[])),
    path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),

    path('sql/', include('sql.urls', namespace='sql')),
]

assets/models.py
from django.db import models


class Ecs(models.Model):
    TYPE_CHOICES = (
        ('阿里云', '阿里云'),
        ('腾讯云', '腾讯云'),
        ('华为云', '华为云'),
        ('亚马逊', '亚马逊'),
        ('其他', '其他'),
        (None,None),
    )
    hostname = models.CharField(max_length=96, verbose_name='主机名', blank=True, null=True, )
    type = models.CharField(choices=TYPE_CHOICES, max_length=16, verbose_name='主机类型', blank=True, null=True, )
    instance_id = models.CharField(max_length=64, verbose_name='实例ID', unique=True)
    instance_name = models.CharField(max_length=96, verbose_name='标签', blank=True, null=True, )
    os_name = models.CharField(max_length=64, verbose_name='系统版本', blank=True, null=True, )
    cpu = models.IntegerField(verbose_name='CPU', blank=True, null=True)
    memory = models.IntegerField(verbose_name='内存', blank=True, null=True)
    private_ip = models.GenericIPAddressField(verbose_name='内网IP', blank=True, null=True)
    public_ip = models.GenericIPAddressField(verbose_name='外网IP', blank=True, null=True)

    c_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间', blank=True)
    u_time = models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间', blank=True)

    class Meta:
        db_table = "ecs"
        verbose_name = "主机"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.hostname

assets/views.py
import logging
import json
from django.urls import reverse_lazy
from django.db.models import Q
from django.conf import settings
from pure_pagination import PageNotAnInteger
from pure_pagination import Paginator
from django.shortcuts import render, HttpResponse
from system.decorator.get_list import get_list
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, View, DetailView, CreateView, UpdateView
from assets.models import Ecs
from assets.form import EcsForm
from assets.serializers import EcsSerializer
from rest_framework import permissions
from rest_framework import generics
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from rest_framework.views import APIView
from rest_framework.response import Response

logger = logging.getLogger('assets')


## 关于 cbv 的 文档 http://ccbv.co.uk/projects/Django/2.1/django.views.generic.edit/
class EcsCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    Ecs 创建
    """
    permission_required = ('assets.add_ecs',)
    model = Ecs
    form_class = EcsForm
    template_name = 'assets/ecs-create.html'
    success_url = reverse_lazy('assets:ecs-list')

    def get_context_data(self, **kwargs):
        context = {}
        if '__next__' in self.request.POST:  # 为了获取 点击本页之前的 浏览网页
            context['i__next__'] = self.request.POST['__next__']
        else:
            try:
                context['i__next__'] = self.request.META['HTTP_REFERER']
            except Exception as e:
                logger.error(e)
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return self.request.POST['__next__']

    def form_valid(self, form):  #  保存结果 可以进行 手动 修改 再保存
        obj = form.save(commit=False)
        obj.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        """If the form is invalid, render the invalid form."""
        return self.render_to_response(self.get_context_data(form=form))


class EcsListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = ('assets.view_ecs',)
    template_name = 'assets/ecs-list.html'
    model = Ecs
    queryset = Ecs.objects.get_queryset().order_by('-id')

    @get_list  ## 处理查询
    def get_context_data(self, **kwargs):
        try:
            page = self.request.GET.get('page', 1)
        except PageNotAnInteger as e:
            page = 1
        p = Paginator(self.queryset, getattr(settings, 'DISPLAY_PER_PAGE'), request=self.request)
        ecs_list = p.page(page)

        context = {
            "ecs_list": ecs_list,
            "filter_dict": self.filter_dict  # 把查询条件返回给前端
        }

        kwargs.update(context)
        return super().get_context_data(**kwargs)


class EcsUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Ecs 更新
    """
    permission_required = ('assets.change_ecs',)
    model = Ecs
    form_class = EcsForm
    template_name = 'assets/ecs-create.html'
    success_url = reverse_lazy('assets:ecs-list')

    def get_context_data(self, **kwargs):
        context = {}
        if '__next__' in self.request.POST:  # 为了获取 点击本页之前的 浏览网页
            context['i__next__'] = self.request.POST['__next__']
        else:
            try:
                context['i__next__'] = self.request.META['HTTP_REFERER']
            except Exception as e:
                logger.error(e)
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return self.request.POST['__next__']


class EcsDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = ('assets.view_ecs',)
    model = Ecs
    form_class = EcsForm
    template_name = 'assets/ecs-detail.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        context = {
            "ecs": self.model.objects.get(id=pk),
            "nid": pk
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class EcsDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """
    Ecs 删除
    """
    permission_required = ('asset.delete_ecs',)
    model = Ecs

    def post(self, request):
        ret = {'status': True, 'error': None, }
        nid = self.request.POST.get('nid', None)
        self.model.objects.get(id=nid).delete()
        return HttpResponse(json.dumps(ret))


# Ecs Api           drf 中文文档   http://drf.jiuyou.info/#/drf/requests
class ApiEcsList(generics.ListCreateAPIView):
    queryset = Ecs.objects.get_queryset().order_by('id')
    serializer_class = EcsSerializer
    filter_backends = (DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter)
    filter_fields = ('id', 'hostname','type','instance_id')
    search_fields = ('id', 'hostname',)
    permission_classes = (permissions.DjangoModelPermissions,)  # 继承 django的权限


class ApiEcsDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Ecs.objects.get_queryset().order_by('id')
    serializer_class = EcsSerializer
    permission_classes = (permissions.DjangoModelPermissions,)

templates/assets/ecs-create.html
{% extends "base/base.html" %}
{% load bootstrap3 %}
{% block  title %}资产添加/修改{% endblock %}
{% block header-css %}

{% endblock %}


{% block page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">
           <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>资产添加/修改</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <form enctype="multipart/form-data" method="post" class="form-horizontal" action="">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本</h3>
                                {% bootstrap_field form.hostname layout="horizontal" %}
                                {% bootstrap_field form.type layout="horizontal" %}
                                {% bootstrap_field form.instance_id layout="horizontal" %}
                                {% bootstrap_field form.instance_name layout="horizontal" %}
                                {% bootstrap_field form.os_name layout="horizontal" %}
                                {% bootstrap_field form.cpu layout="horizontal" %}
                                {% bootstrap_field form.memory layout="horizontal" %}
                                {% bootstrap_field form.private_ip layout="horizontal" %}
                                {% bootstrap_field form.public_ip layout="horizontal" %}
                            </div>
                        </div>


                        <input type="hidden" name="__next__" value="{{ i__next__ }}">
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                                <a class="btn btn-white" href="{{ i__next__ }}">取消</a>

                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>
    </div>




    {% block footer-js %}

        <script>
            window.onload = function () {
                $(".assets").addClass("active");
                $(".ecs-create").addClass("active");
            }
        </script>

    {% endblock %}



{% endblock %}

templates/assets/ecs-detail.html
{% extends "base/base.html" %}
{% block  title %}资产详情{% endblock %}
{% block header-css %}
{% load bootstrap3 %}
{% endblock %}


{% block  page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a class="text-center"><i class="fa fa-laptop"></i>资产详情</a>
                            </li>



                        </ul>
                    </div>

                    <div class="tab-content">
                        <div class="col-sm-7" style="padding-left: 0">
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <span class="label"><b>{{ ecs.hostname }}</b></span>
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>

                                        <a class="close-link">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="ibox-content">

                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <td style=" border-top: none !important;" width="20%">主机类型:</td>
                                            <td style=" border-top: none !important;"><b>{{ ecs.get_type_display }}</b>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="20%">实例ID:</td>
                                            <td><b>{{ ecs.instance_id }}</b>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="20%">标签:</td>
                                            <td><b>{{ ecs.instance_name }}</b>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td width="20%">系统版本:</td>
                                            <td><b>{{ ecs.os_name }}</b>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td width="20%">CPU:</td>
                                            <td><b>{{ ecs.cpu }}</b>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td width="20%">内存:</td>
                                            <td><b>{{ ecs.memory }}</b>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="20%">内网IP:</td>
                                            <td><b>{{ ecs.private_ip }}</b>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="20%">外网IP:</td>
                                            <td><b>{{ ecs.public_ip }}</b>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="20%">创建时间:</td>
                                            <td><b>{{ ecs.c_time }}</b>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="20%">更新时间:</td>
                                            <td><b>{{ ecs.u_time }}</b>
                                            </td>
                                        </tr>


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </div>




    {% block footer-js %}
        <script>
            window.onload = function () {
                $(".assets").addClass("active");
                $(".ecs-list").addClass("active");
            };



        </script>


    {% endblock %}


{% endblock %}

templates/assets/ecs-list.html
{% extends "base/base.html" %}
{% load asset_filter %}
{% load bootstrap3 %}
{% load  static %}
{% block header-css %}

    <style type="text/css">
        .sort_both_png {
            background: url('/static/img/sort_both.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_asc_png {
            background: url('/static/img/sort_asc.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_desc_png {
            background: url('/static/img/sort_desc.png') no-repeat right 1px center;
            cursor: pointer;
        }


    </style>



{% endblock %}

{% block  title %}资产列表{% endblock %}



{% block page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>资产列表</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form id="cha" class="form-horizontal" action="{% url 'assets:ecs-list' %}" method="GET">
                            {% csrf_token %}
                            <div class="row">

                                <div class="col-sm-2">
                                    <input class="form-control input-sm" type="text" name="hostname__icontains"
                                           id="hostname"
                                           placeholder="主机名" style=""/>
                                </div>

                                <div class="col-sm-2">
                                    <select class="input-sm form-control select2   inline" name="type" id="type">
                                        <option value="">主机类型</option>
                                        {% for i in  ''|ecs_type_choices %}

                                            <option value="{{ i.0 }}">{{ i.1 }}</option>

                                        {% endfor %}
                                    </select>


                                </div>

                                <div class="col-sm-2">

                                    <button type="submit" class="btn btn-sm btn-primary"> 搜索</button>
                                </div>
                            </div>
                        </form>
                        <br/>

                        <div class="table-responsive">



                            <form class="form-horizontal  "
                                  method="post">
                                {% csrf_token %}
                                <table class="table table-striped table-bordered table-hover dataTables-code">
                                    <thead>
                                    <tr>


                                        <th>主机名</th>
                                        <th>主机类型</th>

                                        <th>实例ID</th>
                                        <th>标签</th>
                                        <th>系统版本</th>
                                        <th>内网IP</th>

                                        <th  {% if request.GET.order_by == "-c_time" %}
                                            class="sort_asc_png" onclick="window.location.href='?order_by=c_time'"
                                        {% elif request.GET.order_by == "c_time" %}
                                            class="sort_desc_png"
                                            onclick="window.location.href='?order_by=-c_time'"
                                        {% else %}
                                            class="sort_both_png" onclick="window.location.href='?order_by=c_time'"
                                        {% endif %}>创建时间
                                        </th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for   row   in   ecs_list.object_list %}

                                        <tr class="gradeA" id="{{ row.id }}" name="{{ row.hostname }}">


                                            <td class="center">
                                                <div class="">{{ row.hostname }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ row.get_type_display }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ row.instance_id }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ row.instance_name }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ row.os_name }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ row.private_ip }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ row.c_time |  date:'Y-m-d' }}</div>
                                            </td>
                                            <td>
                                          {% if perms.assets.view_ecs %}
                                                    <a class="btn btn-success  btn-xs "
                                                       href="{% url  "assets:ecs-detail" pk=row.id %}">详情</a>
                                                {% endif %}
                                                {% if perms.assets.change_ecs %}
                                                    <a class="btn btn-primary  btn-xs "
                                                       href="{% url  "assets:ecs-update" pk=row.id %}">编辑</a>
                                                {% endif %}
                                                {% if perms.assets.delete_ecs %}
                                                    <a class="btn btn-danger  btn-xs ecs-delete"
                                                       href="#">删除</a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>

                                             <div style="text-align:center;">

                                    <nav class="pagination">
                                        <li><a href="{% url "assets:ecs-list" %}?page=1">首页 </a></li>

                                        {% if ecs_list.has_previous %}
                                            <li class="long"><a
                                                    href="?{{ ecs_list.previous_page_number.querystring }}">上一页</a>
                                            </li>
                                        {% endif %}

                                        {% for page in ecs_list.pages %}
                                            {% if page %}
                                                {% ifequal page ecs_list.number %}
                                                    <li class="active"  ><a style="background-color: #E0E0E0" href="?{{ page.querystring }}">{{ page }}</a>
                                                    </li>
                                                {% else %}
                                                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                                                    </li>
                                                {% endifequal %}
                                            {% else %}
                                                <li class="none"><a href="">...</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if ecs_list.has_next %}
                                            <li class="long"><a
                                                    href="?{{ ecs_list.next_page_number.querystring }}">下一页</a>
                                            </li>
                                        {% endif %}
                                        <li>
                                            <a href="{% url "assets:ecs-list" %}?page={{ ecs_list.paginator.num_pages }}">尾页 </a>
                                        </li>
                                        <li><span
                                                style="color: #0a0a0a">总: &nbsp;{{ ecs_list.paginator.num_pages }} 页</span>
                                        </li>
                                        <li><span
                                                style="color: #0a0a0a"> 数量: {{ ecs_list.paginator.count  }}</span>
                                        </li>
                                    </nav>
                                </div>


                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}

        <script>
            window.onload = function () {   // 固定左边导航栏
                $(".assets").addClass("active");
                $(".ecs-list").addClass("active");
            };


            var filter_dict = {{ filter_dict | safe}};   // 搜索完之后，还能保存搜索项目
            $("#hostname").val(filter_dict['hostname__icontains']);
            $("#type").val(filter_dict['type']);


            $(function () {

                $(document).on('click', '.ecs-delete', function () {
                    var id = $(this).parent().parent().attr('id');
                    var name = $(this).parent().parent().attr('name');
                    swal({
                        title: "你确定删除",
                        text: name,
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        cancelButtonText: "取消",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "{% url 'assets:ecs-delete' %}",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });
                    });

                });


            });

        </script>
    {% endblock %}

{% endblock %}