k8s/urls.py
from django.urls import path
from k8s import views

app_name = "k8s"

urlpatterns = [
    path('k8s-node-list', views.K8sNodeListView.as_view(), name='k8s-node-list'),

    path('k8s-service-list', views.K8sServiceListView.as_view(), name='k8s-service-list'),

    path('k8s-pod-list', views.K8sPodListView.as_view(), name='k8s-pod-list'),
    path('k8s-pod-webssh', views.K8sPodWebssh.as_view(), name='k8s-pod-webssh'),
    path('k8s-pod-detail', views.K8sPodDetail.as_view(), name='k8s-pod-detail')
]

seal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from system.views import index
from rest_framework.authtoken import views
from rest_framework.documentation import include_docs_urls
from graphene_django.views import GraphQLView
from seal.schema import schema

API_TITLE = '海豹 API 文档'
API_DESCRIPTION = '海豹 API 文档'

urlpatterns = [
    path('', index),
    path('index', index, name="index"),
    path('system/', include('system.urls', namespace='system')),
    path('assets/', include('assets.urls', namespace='assets')),
    path('k8s/', include('k8s.urls', namespace='k8s')),
    path('admin/', admin.site.urls, ),
    path('api/token', views.obtain_auth_token),
    path('api/docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION, authentication_classes=[],
                                        permission_classes=[])),
    path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),

    path('sql/', include('sql.urls', namespace='sql')),
]

k8s/models.py
from django.db import models

k8s/views.py
import logging
import json
from django.urls import reverse_lazy
from django.db.models import Q
from django.conf import settings
from pure_pagination import PageNotAnInteger
from pure_pagination import Paginator
from django.shortcuts import render, HttpResponse
from system.decorator.get_list import get_list
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, View, DetailView, CreateView, UpdateView
from assets.models import Ecs
from seal import settings
from k8s.k8sApi.core import K8sApi

logger = logging.getLogger('k8s')


class K8sNodeListView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('k8s.view_ecs',)

    def get(self, request):
        obj = K8sApi()
        ret = obj.get_node_list()
        data = {}
        for i in ret.items:
            data[i.metadata.name] = {"name": i.metadata.name,
                                     "status": i.status.conditions[-1].type if i.status.conditions[ -1].status == "True" else "NotReady",
                                     "ip": i.status.addresses[0].address,
                                     "kubelet_version": i.status.node_info.kubelet_version,
                                     "os_image": i.status.node_info.os_image,
                                     }
        return render(request, "k8s/k8s-node-list.html", {"data": data})


class K8sServiceListView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('k8s.view_ecs',)

    def get(self, request):
        obj = K8sApi()
        ret = obj.get_service_list()
        data = {}
        for i in ret.items:
            print(i)
            ports = []
            for j in i.spec.ports:
                ports.append(f"{j.target_port}/{j.port}/{j.node_port}")
            data[i.metadata.name] = {"name": i.metadata.name, "cluster_ip": i.spec.cluster_ip, "type": i.spec.type,
                                     "external_i_ps": i.spec.external_i_ps,
                                     "port": ports}
        return render(request, "k8s/k8s-service-list.html", {"data": data})


class K8sPodListView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('k8s.view_ecs',)

    def get(self, request):
        obj = K8sApi()
        ret = obj.get_pod_list()
        data = {}
        for i in ret.items:
            data[i.metadata.name] = {"ip": i.status.pod_ip, "namespace": i.metadata.namespace}
        return render(request, "k8s/k8s-pod-list.html", {"data": data})


class K8sPodWebssh(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('k8s.view_ecs',)

    def get(self, request):
        name = self.request.GET.get("name")
        namespace = self.request.GET.get("namespace")
        return render(request, "k8s/k8s-pod-webssh.html", {"name": name, "namespace": namespace})


class K8sPodDetail(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('k8s.view_ecs',)

    def get(self, request):
        name = self.request.GET.get("name")
        namespace = self.request.GET.get("namespace")
        obj = K8sApi()
        data = obj.get_pod_detail(name, namespace)
        return render(request, "k8s/k8s-pod-detail.html", {"name": name, "namespace": namespace, "data": data})

templates/k8s/k8s-node-list.html
{% extends "base/base.html" %}
{% load asset_filter %}
{% load bootstrap3 %}
{% load  static %}
{% block header-css %}

    <style type="text/css">
        .sort_both_png {
            background: url('/static/img/sort_both.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_asc_png {
            background: url('/static/img/sort_asc.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_desc_png {
            background: url('/static/img/sort_desc.png') no-repeat right 1px center;
            cursor: pointer;
        }


    </style>



{% endblock %}

{% block  title %}K8S{% endblock %}



{% block page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>Node列表</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">



                        <div class="table-responsive">


                            <form class="form-horizontal  "
                                  method="post">
                                {% csrf_token %}
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>


                                        <th>服务名</th>
                                        <th>状态</th>
                                        <th>IP</th>
                                        <th>版本</th>
                                        <th>镜像</th>
                                        <th>IP</th>
                                        <th>IP</th>



                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for   k,v  in   data.items  %}

                                        <tr class="gradeA" id="{{ row.id }}" name="{{ k }}">


                                            <td class="center">
                                                <div class="">{{ k }}</div>
                                            </td>
                                            <td class="center">
                                                {% if v.status == "Ready" %}
                                                <div class="btn btn-success  btn-xs"> {{ v.status }}</div>
                                                {% else %}
                                                    <div class="btn btn-danger  btn-xs"> {{ v.status }}</div>
                                                {% endif %}
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.ip}}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.kubelet_version}}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.os_image}}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.ip}}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.ip}}</div>
                                            </td>


                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>

                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}

        <script>
            window.onload = function () {   // 固定左边导航栏
                $(".k8s").addClass("active");
                $(".k8s-node-list").addClass("active");
            };

        </script>
    {% endblock %}

{% endblock %}

templates/k8s/k8s-pod-detail.html
{% extends "base/base.html" %}
{% block  title %}资产详情{% endblock %}
{% block header-css %}
{% load bootstrap3 %}
{% endblock %}


{% block  page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a class="text-center"><i class="fa fa-laptop"></i>{{ name }}</a>
                            </li>



                        </ul>
                    </div>

                    <div class="tab-content">
                        <div class="col-sm-12" style="padding-left: 0">
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <span class="label"><b>{{ name }}</b></span>
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>

                                        <a class="close-link">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="ibox-content">

                                    <pre>{{ data }}
                                    </pre>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </div>




    {% block footer-js %}
        <script>
            window.onload = function () {   // 固定左边导航栏
                $(".k8s").addClass("active");
                $(".k8s-pod-list").addClass("active");
            };

        </script>


    {% endblock %}


{% endblock %}

templates/k8s/k8s-pod-list.html
{% extends "base/base.html" %}
{% load asset_filter %}
{% load bootstrap3 %}
{% load  static %}
{% block header-css %}

    <style type="text/css">
        .sort_both_png {
            background: url('/static/img/sort_both.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_asc_png {
            background: url('/static/img/sort_asc.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_desc_png {
            background: url('/static/img/sort_desc.png') no-repeat right 1px center;
            cursor: pointer;
        }


    </style>



{% endblock %}

{% block  title %}K8S{% endblock %}



{% block page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>Pod列表</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">



                        <div class="table-responsive">


                            <form class="form-horizontal  "
                                  method="post">
                                {% csrf_token %}
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>


                                        <th>主机名</th>
                                        <th>ip</th>
                                        <th>命名空间</th>
                                          <th>详情</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for   k,v  in   data.items  %}

                                        <tr class="gradeA" id="{{ row.id }}" name="{{ k }}">


                                            <td class="center">
                                                <div class="">{{ k }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.ip }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.namespace}}</div>
                                            </td>
                                                                                        <td class="center">
                                                 <a class="btn btn-warning  btn-xs "  target="_blank"
                                                       href="{% url  "k8s:k8s-pod-detail" %}?namespace={{ v.namespace }}&name={{ k }}">详情</a>
                                            </td>

                                            <td class="center">
                                                 <a class="btn btn-success  btn-xs "  target="_blank"
                                                       href="{% url  "k8s:k8s-pod-webssh" %}?namespace={{ v.namespace }}&name={{ k }}">webssh</a>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>

                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}

        <script>
            window.onload = function () {   // 固定左边导航栏
                $(".k8s").addClass("active");
                $(".k8s-pod-list").addClass("active");
            };

        </script>
    {% endblock %}

{% endblock %}

templates/k8s/k8s-pod-webssh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>django webssh 例子</title>


    <link href="https://cdnjs.cloudflare.com/ajax/libs/xterm/3.13.2/xterm.css" rel="stylesheet" type="text/css"/>

</head>
<body>


<div id="terms"></div>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/xterm/3.13.2/xterm.js"></script>


<script>
    var socket = new WebSocket('ws://' + window.location.host + '/ws/{{ name }}/{{ namespace }}');

    socket.onopen = function () {

        var term = new Terminal();
        term.open(document.getElementById('terms'));


        term.on('data', function (data) {
            console.log(data);
            socket.send(data);
        });

        socket.onmessage = function (msg) {
            console.log(msg);
            console.log(msg.data);
            term.write(msg.data);
        };
        socket.onerror = function (e) {
            console.log(e);
        };

        socket.onclose = function (e) {
            console.log(e);
            term.destroy();
        };
    };


</script>


</html>

templates/k8s/k8s-service-list.html
{% extends "base/base.html" %}
{% load asset_filter %}
{% load bootstrap3 %}
{% load  static %}
{% block header-css %}

    <style type="text/css">
        .sort_both_png {
            background: url('/static/img/sort_both.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_asc_png {
            background: url('/static/img/sort_asc.png') no-repeat right 1px center;
            cursor: pointer;
        }

        .sort_desc_png {
            background: url('/static/img/sort_desc.png') no-repeat right 1px center;
            cursor: pointer;
        }


    </style>



{% endblock %}

{% block  title %}K8S{% endblock %}



{% block page-content %}


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>Service列表</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">



                        <div class="table-responsive">


                            <form class="form-horizontal  "
                                  method="post">
                                {% csrf_token %}
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>


                                        <th>服务名</th>
                                        <th>cluster_ip</th>
                                        <th>类型</th>
                                         <th>external_i_ps</th>

                                         <th>target_port/port/node_port</th>



                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for   k,v  in   data.items  %}

                                        <tr class="gradeA" id="{{ row.id }}" name="{{ k }}">


                                            <td class="center">
                                                <div class="">{{ k }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.cluster_ip }}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.type}}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{{ v.external_i_ps}}</div>
                                            </td>
                                            <td class="center">
                                                <div class="">{% for i in v.port %}{{ i }} <br />{% endfor %}</div>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>

                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}

        <script>
            window.onload = function () {   // 固定左边导航栏
                $(".k8s").addClass("active");
                $(".k8s-service-list").addClass("active");
            };

        </script>
    {% endblock %}

{% endblock %}